defaults: &defaults
  working_directory: /usr/src/app
  docker:
    - image: aa8y/sbt:ci

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - build-dependencies-{{ checksum "build.sbt" }}
          - sbt-dependencies--{{ checksum "project/build.properties" }}
      # Resource of Docker Executor - 2 vCPUs and 4GB
      - run:
          environment:
            SBT_OPTS: "-XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:MetaspaceSize=256M -XX:MaxMetaspaceSize=512M -Xmx2G"
          command: sbt clean coverage +test
      - run:
          environment:
            SBT_GHPAGES_COMMIT_MESSAGE: 'Publishing Scaladoc [ci skip]'
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              sbt updateImpactSubmit coverageReport coverageAggregate codacyCoverage
              /bin/bash <(wget --quiet https://codecov.io/bash)
              git config --global user.email "pathikritbhowmick@msn.com"
              git config --global user.name "circle-ci"
              git config --global push.default simple
              mkdir ~/.ssh && ssh-keyscan github.com > ~/.ssh/known_hosts
              sbt ghpagesPushSite +publish
            fi
      - save_cache:
          paths:
            - ~/.ivy2/cache
            - ~/.m2
          key: build-dependencies--{{ checksum "build.sbt" }}
      - save_cache:
          paths:
            - ~/.sbt
          key: sbt-dependencies--{{ checksum "project/build.properties" }}
      - persist_to_workspace:
          root: /usr/src
          paths:
            - app
